version: '3.8'
services:
  web:
    build: .
    command: flask run
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}

  worker:
    build: .
    command: python worker.py
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: museum_db
    ports:
      - "9090:5432"
