apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: museum-db
  namespace: museum-namespace
spec:
  serviceName: "museum-db"
  replicas: 1
  selector:
    matchLabels:
      app: museum-db
  template:
    metadata:
      labels:
        app: museum-db
    spec:
      containers:
        - name: postgres
          image: postgres:13  # Using stable version
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: museum-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: museum-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: museum-config
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: museum-db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: museum-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi